inherits:
    - strictness_high

ignore-patterns:
  - ^\..+
  - ^(build|data|dist|.*egg-info)/

test-warnings: true

output-format: grouped

dodgy:
    run: true

frosted:
    run: true

mccabe:
    run: true

pep257:
    run: true

pep8:
    run: true

pyflakes:
    # preferring 'frosted' instead
    run: false

pylint:
    run: true
    disable:
        # Invalid module name "wcwidth-browser"
        - C0103

pyroma:
    run: true

vulture:
    run: false

# vim: noai:ts=4:sw=4
