/*
 * Binary search in Unicode interval tables.
 */
#ifndef WCWIDTH_TABLES_H
#define WCWIDTH_TABLES_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * An interval [start, end] (inclusive) in Unicode codepoint space.
 */
typedef struct
{
    uint32_t start;
    uint32_t end;
} wcwidth_interval_t;

/*
 * Binary search for *ucs* in a sorted interval table.
 *
 * Returns 1 if *ucs* is contained within any interval in *table*, 0 otherwise.
 *
 * *table* must be sorted ascending, with non-overlapping intervals.
 */
int wcwidth_bisearch(uint32_t ucs, const wcwidth_interval_t *table, size_t table_len);

extern const wcwidth_interval_t WCWIDTH_TABLE_WIDE[];

extern const wcwidth_interval_t WCWIDTH_TABLE_ZERO[];

extern const wcwidth_interval_t WCWIDTH_TABLE_AMBIGUOUS[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_EXTEND[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_CR[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LF[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_ZWJ[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_L[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_V[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_T[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LV[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LVT[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_PREPEND[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_SPACINGMARK[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_CONTROL[];

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_REGIONAL_INDICATOR[];

extern const wcwidth_interval_t WCWIDTH_TABLE_EXTENDED_PICTOGRAPHIC[];

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_LINKER[];

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_CONSONANT[];

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_EXTEND[];

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_CONSONANT[];

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_VIRAMA[];

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_INVISIBLE_STACKER[];

extern const wcwidth_interval_t WCWIDTH_TABLE_MC[];

extern const wcwidth_interval_t WCWIDTH_TABLE_VS15[];

extern const wcwidth_interval_t WCWIDTH_TABLE_VS16[];

/*
 * Terminal override tables (generated by update-tables.py).
 *
 * The six single-codepoint categories are the merged override intervals;
 * grapheme clusters are stored as a flat codepoint pool with sorted lookup
 * entries.
 */
typedef struct
{
    const wcwidth_interval_t *narrower;
    size_t narrower_len;
    const wcwidth_interval_t *vs16_narrower;
    size_t vs16_narrower_len;
    const wcwidth_interval_t *vs15_wider;
    size_t vs15_wider_len;
    const wcwidth_interval_t *zeroer;
    size_t zeroer_len;
    const wcwidth_interval_t *narrow_wider;
    size_t narrow_wider_len;
    const wcwidth_interval_t *narrow_zeroer;
    size_t narrow_zeroer_len;
} wcwidth_override_set_t;

typedef struct
{
    uint32_t offset; /* into the table's grapheme codepoint pool */
    uint16_t len;    /* codepoints in the cluster */
    uint8_t width;   /* terminal-measured width */
} wcwidth_grapheme_entry_t;

typedef struct
{
    const char *name; /* canonical terminal name */
    const wcwidth_override_set_t *set;
    const uint32_t *grapheme_pool;
    size_t grapheme_pool_len;
    const wcwidth_grapheme_entry_t *grapheme_entries;
    size_t grapheme_entries_len;
} wcwidth_terminal_override_t;

typedef struct
{
    const char *alias;      /* TERM/TERM_PROGRAM value, lowercase */
    const char *canonical;  /* canonical terminal name */
} wcwidth_terminal_alias_t;

extern const wcwidth_terminal_override_t WCWIDTH_TERMINAL_OVERRIDES[];

extern const wcwidth_terminal_alias_t WCWIDTH_TERMINAL_ALIASES[];

#ifdef __cplusplus
}
#endif

#endif /* WCWIDTH_TABLES_H */
