/*
 * Generated by wcwidth code generation (update-tables.py).
 *
 * External declarations for every generated table -- the Unicode interval
 * tables and the terminal override/alias arrays -- each with a compile-time
 * length macro (entry counts are codegen-known).
 *
 * Do not edit; see code_templates/tables.h.j2.
 */
#ifndef WCWIDTH_TABLES_H
#define WCWIDTH_TABLES_H

#include "wcwidth/table_types.h"

#ifdef __cplusplus
extern "C" {
#endif

extern const wcwidth_interval_t WCWIDTH_TABLE_WIDE[];
#define WCWIDTH_TABLE_WIDE_LEN 125

extern const wcwidth_interval_t WCWIDTH_TABLE_ZERO[];
#define WCWIDTH_TABLE_ZERO_LEN 337

extern const wcwidth_interval_t WCWIDTH_TABLE_AMBIGUOUS[];
#define WCWIDTH_TABLE_AMBIGUOUS_LEN 176

extern const wcwidth_interval_t WCWIDTH_TABLE_MC[];
#define WCWIDTH_TABLE_MC_LEN 193

extern const wcwidth_interval_t WCWIDTH_TABLE_VS15[];
#define WCWIDTH_TABLE_VS15_LEN 91

extern const wcwidth_interval_t WCWIDTH_TABLE_VS16[];
#define WCWIDTH_TABLE_VS16_LEN 113

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_CR[];
#define WCWIDTH_TABLE_GRAPHEME_CR_LEN 1

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LF[];
#define WCWIDTH_TABLE_GRAPHEME_LF_LEN 1

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_EXTEND[];
#define WCWIDTH_TABLE_GRAPHEME_EXTEND_LEN 384

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_ZWJ[];
#define WCWIDTH_TABLE_GRAPHEME_ZWJ_LEN 1

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_L[];
#define WCWIDTH_TABLE_GRAPHEME_L_LEN 2

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_V[];
#define WCWIDTH_TABLE_GRAPHEME_V_LEN 4

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_T[];
#define WCWIDTH_TABLE_GRAPHEME_T_LEN 2

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LV[];
#define WCWIDTH_TABLE_GRAPHEME_LV_LEN 399

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_LVT[];
#define WCWIDTH_TABLE_GRAPHEME_LVT_LEN 399

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_PREPEND[];
#define WCWIDTH_TABLE_GRAPHEME_PREPEND_LEN 15

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_SPACINGMARK[];
#define WCWIDTH_TABLE_GRAPHEME_SPACINGMARK_LEN 158

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_CONTROL[];
#define WCWIDTH_TABLE_GRAPHEME_CONTROL_LEN 19

extern const wcwidth_interval_t WCWIDTH_TABLE_GRAPHEME_REGIONAL_INDICATOR[];
#define WCWIDTH_TABLE_GRAPHEME_REGIONAL_INDICATOR_LEN 1

extern const wcwidth_interval_t WCWIDTH_TABLE_EXTENDED_PICTOGRAPHIC[];
#define WCWIDTH_TABLE_EXTENDED_PICTOGRAPHIC_LEN 156

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_LINKER[];
#define WCWIDTH_TABLE_INCB_LINKER_LEN 20

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_CONSONANT[];
#define WCWIDTH_TABLE_INCB_CONSONANT_LEN 76

extern const wcwidth_interval_t WCWIDTH_TABLE_INCB_EXTEND[];
#define WCWIDTH_TABLE_INCB_EXTEND_LEN 377

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_CONSONANT[];
#define WCWIDTH_TABLE_ISC_CONSONANT_LEN 162

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_VIRAMA[];
#define WCWIDTH_TABLE_ISC_VIRAMA_LEN 27

extern const wcwidth_interval_t WCWIDTH_TABLE_ISC_INVISIBLE_STACKER[];
#define WCWIDTH_TABLE_ISC_INVISIBLE_STACKER_LEN 14

extern const wcwidth_terminal_override_t WCWIDTH_TERMINAL_OVERRIDES[];
#define WCWIDTH_TERMINAL_OVERRIDES_LEN 23

extern const wcwidth_terminal_alias_t WCWIDTH_TERMINAL_ALIASES[];
#define WCWIDTH_TERMINAL_ALIASES_LEN 11

#ifdef __cplusplus
}
#endif

#endif /* WCWIDTH_TABLES_H */
