"""
Grapheme overrides for _known_9363f6e6.

This code generated by python wcwidth project from ucs-detect data.

Terminals: iterm2
"""
# pylint: skip-file
GRAPHEMES = {
    '⛹🏻\u200d♀️': 3,
    '⛹🏻\u200d♂️': 3,
    '⛹🏼\u200d♀️': 3,
    '⛹🏼\u200d♂️': 3,
    '⛹🏽\u200d♀️': 3,
    '⛹🏽\u200d♂️': 3,
    '⛹🏾\u200d♀️': 3,
    '⛹🏾\u200d♂️': 3,
    '⛹🏿\u200d♀️': 3,
    '⛹🏿\u200d♂️': 3,
}
