"""
Terminal -> grapheme override hash registry.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file
_REGISTRY = {
    'alacritty': '64d2e864',
    'apple_terminal': 'e3dfb784',
    'bobcat': '80323663',
    'contour': '57832def',
    'extraterm': '8cd917bd',
    'gnu screen': 'e6e5d1f4',
    'iterm2': '9363f6e6',
    'konsole': 'c0cc47ea',
    'libvterm': '146468f1',
    'mintty': '2de11ac2',
    'mlterm': 'e3dfb784',
    'pterm': 'e6e5d1f4',
    'rio': '1cbbebb7',
    'st-luke': '8dc9f9a2',
    'terminology': '0e00865d',
    'tmux': 'a8242ce0',
    'urxvt': '8dc9f9a2',
    'vte': 'e6e5d1f4',
    'warp': '0bccd381',
    'xterm': '8dc9f9a2',
    'xterm.js': 'd5a9ae23',
    'zellij': 'e6e5d1f4',
}

__all__ = ('_REGISTRY',)
