"""
Terminal to grapheme mapping of overrides, using a hash registry.

This code generated by python wcwidth using ucs-detect project data.
"""
# pylint: skip-file
_REGISTRY = {
    'alacritty': '33ac73f2',
    'apple_terminal': 'be45d113',
    'bobcat': '47afe9c6',
    'extraterm': '6ef3cf1c',
    'foot': 'cf02297d',
    'ghostty': 'e2b75ee3',
    'iterm2': 'ae0343b1',
    'kitty': '240ecb8b',
    'konsole': '038dd236',
    'mintty': '799bc71e',
    'mlterm': '4f31559b',
    'pterm': '97904ece',
    'rio': '019493b5',
    'st': 'a5880eeb',
    'terminology': 'fa2bd14d',
    'urxvt': 'a5880eeb',
    'vte': '97904ece',
    'warp': '38feaa10',
    'wezterm': '2148ff29',
    'xterm': 'a5880eeb',
    'xterm.js': '96acc0f7',
}

__all__ = ('_REGISTRY',)
