"""
Terminal to grapheme mapping of overrides, using a hash registry.

This code generated by python wcwidth using ucs-detect project data.
"""
# pylint: skip-file
_REGISTRY = {
    'alacritty': '362c5e5a',
    'apple_terminal': 'ea98604e',
    'bobcat': '035682b1',
    'contour': '73e30d5f',
    'extraterm': '2a1a4696',
    'foot': '09385645',
    'ghostty': '31782517',
    'iterm2': 'cf8e6627',
    'kitty': 'f5113469',
    'konsole': 'ed62aba3',
    'mintty': 'e5d8f55c',
    'mlterm': '2b58bd81',
    'pterm': '51bae070',
    'rio': '74d1883e',
    'st': '99533670',
    'terminology': '4e8151ee',
    'urxvt': '99533670',
    'vte': '51bae070',
    'warp': '7d686339',
    'wezterm': '69889298',
    'xterm': '99533670',
    'xterm.js': '035f76e8',
}

__all__ = ('_REGISTRY',)
