/*
 * Generated by wcwidth code generation (update-tables.py).
 *
 * Canonical terminal names and TERM/TERM_PROGRAM aliases, sorted for binary
 * search.
 */
#include "wcwidth/generated_tables.h"

const wcwidth_terminal_alias_t WCWIDTH_TERMINAL_ALIASES[] = {
    { "hyper", "xterm.js" },
    { "iterm.app", "iterm2" },
    { "putty", "pterm" },
    { "rxvt", "urxvt" },
    { "rxvt-unicode-256color", "urxvt" },
    { "st-256color", "st" },
    { "tabby", "xterm.js" },
    { "vscode", "xterm.js" },
    { "warpterminal", "warp" },
    { "xterm-ghostty", "ghostty" },
    { "xterm-kitty", "kitty" },
};
_Static_assert(sizeof(WCWIDTH_TERMINAL_ALIASES) / sizeof(WCWIDTH_TERMINAL_ALIASES[0])
                   == WCWIDTH_TERMINAL_ALIASES_LEN,
               "WCWIDTH_TERMINAL_ALIASES_LEN out of date");
