"""
wcwidth module.

https://github.com/jquast/wcwidth
"""
# re-export all functions & definitions, even private ones, from top-level
# module path, to allow for 'from wcwidth import _private_func' if necessary.
# Of course, user beware that any _private function may disappear or change
# signature at any future version. This is also a bit odd in that.
#
# This effort flattens the statement, 'from wcwidth.wcwidth import wcwidth' into
# 'from wcwidth import wcwidth'.

# local
from .wcwidth import (
    width,
    wcwidth,
    wcswidth,
    list_versions,
    _wcwidth,
    _wcswidth,
    _bisearch,
    _wcmatch_version,
    _wcversion_value,
    ZERO_WIDTH,
    WIDE_EASTASIAN,
    )
from .emoji_zwj_sequences import EMOJI_ZWJ_SEQUENCES

# The __all__ attribute defines the items exported from statement,
# 'from wcwidth import *', but also to say, "This is the public API"
# that is qualified by semver version number management.
__all__ = ('width', 'wcwidth', 'wcswidth', 'list_versions')

# We also used pkg_resources to load unicode version tables from version.json,
# generated by bin/update-tables.py, but some environments are unable to
# import pkg_resources for one reason or another, yikes!
__version__ = '0.2.8'
