"""
Auto-generated terminal capability patterns.

Generated from terminfo for: xterm, xterm-256color, xterm-direct, alacritty, alacritty-direct, kitty, kitty-direct, ghostty, tmux, tmux-256color, screen, screen-256color, linux, vt100, vt220, rxvt-unicode-256color, konsole-256color

This code generated by wcwidth/bin/update-termcaps.py on 2026-01-13 22:15:57 UTC.

Patterns are organized by their effect on cursor position for use with width():
- HORIZONTAL_MOVEMENT_CAPS: Track in 'parse' mode, calculate distance
- INDETERMINATE_CAPS: Raise ValueError in 'strict' mode
- ZERO_WIDTH_CAPS: Safe, no cursor movement
"""

# Horizontal movement sequences - track in 'parse' mode
HORIZONTAL_MOVEMENT_CAPS = {
    'cursor_right': '\x1b\\[C',
    'parm_left_cursor': '\x1b\\[(\\d+)D',
    'parm_right_cursor': '\x1b\\[(\\d+)C',
}

# Indeterminate/vertical sequences - raise in 'strict' mode
INDETERMINATE_CAPS = {
    'change_scroll_region': '\x1b\\[\\d+;\\d+r',
    'clear_screen': '(?:\x1b\\[H\x1b\\[2J|\x1b\\[H\x1b\\[J)',
    'clr_bol': '\x1b\\[1K',
    'clr_eol': '\x1b\\[K',
    'clr_eos': '\x1b\\[J',
    'column_address': '\x1b\\[\\d+G',
    'cursor_address': '\x1b\\[(\\d+);(\\d+)H',
    'cursor_home': '\x1b\\[H',
    'cursor_up': '(?:\x1bM|\x1b\\[A)',
    'delete_character': '\x1b\\[P',
    'delete_line': '\x1b\\[M',
    'enter_fullscreen': '(?:\x1b7\x1b\\[\\?47h|\x1b\\[\\?1049h|\x1b\\[\\?1049h\x1b\\[22;0;0t)',
    'erase_chars': '\x1b\\[\\d+X',
    'exit_fullscreen': '(?:\x1b\\[2J\x1b\\[\\?47l\x1b8|\x1b\\[\\?1049l|\x1b\\[\\?1049l\x1b\\[23;0;0t|\x1b\\[r\x1b\\[\\?1049l)',
    'insert_line': '\x1b\\[L',
    'parm_dch': '\x1b\\[\\d+P',
    'parm_delete_line': '\x1b\\[\\d+M',
    'parm_down_cursor': '\x1b\\[\\d+B',
    'parm_ich': '\x1b\\[\\d+@',
    'parm_index': '\x1b\\[\\d+S',
    'parm_insert_line': '\x1b\\[\\d+L',
    'parm_rindex': '\x1b\\[\\d+T',
    'parm_up_cursor': '\x1b\\[\\d+A',
    'restore_cursor': '\x1b8',
    'row_address': '\x1b\\[\\d+d',
    'scroll_forward': '\x1bD',
    'scroll_reverse': '\x1bM',
}

# Zero-width sequences - no cursor movement
ZERO_WIDTH_CAPS = {
    'clear_all_tabs': '\x1b\\[3g',
    'cursor_invisible': '(?:\x1b\\[\\?25l|\x1b\\[\\?25l\x1b\\[\\?1c)',
    'cursor_normal': '(?:\x1b\\[34h\x1b\\[\\?25h|\x1b\\[\\?12l\x1b\\[\\?25h|\x1b\\[\\?25h|\x1b\\[\\?25h\x1b\\[\\?0c)',
    'cursor_visible': '(?:\x1b\\[34l|\x1b\\[\\?12;25h|\x1b\\[\\?25h\x1b\\[\\?8c)',
    'enter_alt_charset_mode': '\x1b\\(0',
    'enter_blink_mode': '\x1b\\[5m',
    'enter_bold_mode': '\x1b\\[1m',
    'enter_dim_mode': '\x1b\\[2m',
    'enter_italics_mode': '\x1b\\[3m',
    'enter_reverse_mode': '\x1b\\[7m',
    'enter_standout_mode': '(?:\x1b\\[3m|\x1b\\[7m)',
    'enter_underline_mode': '\x1b\\[4m',
    'exit_alt_charset_mode': '\x1b\\(B',
    'exit_attribute_mode': '(?:\x1b\\(B\x1b\\[m|\x1b\\[0m\x0f|\x1b\\[m\x0f|\x1b\\[m\x1b\\(B)',
    'exit_insert_mode': '\x1b\\[4l',
    'exit_italics_mode': '\x1b\\[23m',
    'exit_standout_mode': '(?:\x1b\\[23m|\x1b\\[27m|\x1b\\[m)',
    'exit_underline_mode': '(?:\x1b\\[24m|\x1b\\[m)',
    'flash_screen': '(?:\x1b\\[\\?5h\x1b\\[\\?5l|\x1bg)',
    'keypad_local': '(?:\x1b>|\x1b\\[\\?1l|\x1b\\[\\?1l\x1b>)',
    'keypad_xmit': '(?:\x1b=|\x1b\\[\\?1h|\x1b\\[\\?1h\x1b=)',
    'orig_pair': '\x1b\\[39;49m',
    'save_cursor': '\x1b7',
    'set_tab': '\x1bH',
}
