"""
Auto-generated terminal capability patterns.

Generated from terminfo for: xterm, xterm-256color, xterm-direct, alacritty, alacritty-direct, kitty, kitty-direct, ghostty, tmux, tmux-256color, screen, screen-256color, linux, vt100, vt220, rxvt-unicode-256color, konsole-256color

This code generated by wcwidth/bin/update-termcaps.py on 2026-01-14 16:41:58 UTC.

INDETERMINATE_CAPS: Patterns that raise ValueError in 'strict' mode.
"""

# Indeterminate/vertical sequences - raise in 'strict' mode
INDETERMINATE_CAPS = {
    'change_scroll_region': '\x1b\\[\\d+;\\d+r',
    'clear_screen': '\x1b\\[H\x1b\\[2J|\x1b\\[H\x1b\\[J',
    'clr_bol': '\x1b\\[1K',
    'clr_eol': '\x1b\\[K',
    'clr_eos': '\x1b\\[J',
    'column_address': '\x1b\\[\\d+G',
    'cursor_address': '\x1b\\[\\d+;\\d+H',
    'cursor_down': '\\x1b\\[\\d*B',
    'cursor_home': '\x1b\\[H',
    'cursor_up': '\x1b\\[A',
    'delete_character': '\x1b\\[P',
    'delete_line': '\x1b\\[M',
    'enter_fullscreen': '\x1b\\[\\?1049h|\x1b\\[\\?47h',
    'erase_chars': '\x1b\\[\\d+X',
    'erase_display': '\\x1b\\[\\d*J',
    'exit_fullscreen': '\x1b8|\x1b\\[\\?1049l|\x1b\\[\\?47l',
    'insert_line': '\x1b\\[L',
    'parm_dch': '\x1b\\[\\d+P',
    'parm_delete_line': '\x1b\\[\\d+M',
    'parm_down_cursor': '\x1b\\[\\d+B',
    'parm_ich': '\x1b\\[\\d+@',
    'parm_index': '\x1b\\[\\d+S',
    'parm_insert_line': '\x1b\\[\\d+L',
    'parm_rindex': '\x1b\\[\\d+T',
    'parm_up_cursor': '\x1b\\[\\d+A',
    'restore_cursor': '\x1b8',
    'row_address': '\x1b\\[\\d+d',
    'scroll_forward': '\x1bD',
    'scroll_reverse': '\x1bM',
}
