"""
Exports SFZ_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth using ucs-detect project data.
"""
# pylint: skip-file

# For terminals: foot
_SET_DFEF2777 = {
    'narrower': (
        (0x1f3fb, 0x1f3ff,),  # Emoji Modifier Fitzpatri..Emoji Modifier Fitzpatri
    ),
    'wider': (
    ),
}


SFZ_OVERRIDES = {
    'foot': _SET_DFEF2777,
}
