"""
Exports SRI_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: disable=duplicate-code
SRI_OVERRIDES = {
    'extraterm': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'putty': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'rio': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'teraterm': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'terminal.app': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'terminal.exe': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'vte': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'wezterm': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'xterm': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'zellij': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'alacritty': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'cmd.exe': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'foot': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'mlterm': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'qtermwidget': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'rxvt-unicode': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'screen': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'securecrt': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'st': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'terminology': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'weston-terminal': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'xterm.js': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
    'zutty': {
        'narrower': (
            (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
        ),
        'wider': (
        ),
    },
}
