"""
Exports SFZ_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file
_SET_5C6E47B5 = {
    'narrower': (
        (0x1f3fb, 0x1f3ff,),  # EMOJI MODIFIER FITZPATRI..EMOJI MODIFIER FITZPATRI
    ),
    'wider': (
    ),
}


SFZ_OVERRIDES = {
    'terminal.exe': _SET_5C6E47B5,
    'cmd.exe': _SET_5C6E47B5,
    'foot': _SET_5C6E47B5,
}
