"""
Exports SFZ_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: disable=duplicate-code
SFZ_OVERRIDES = {
    'terminal.exe': {
        'narrower': (
            (0x1f3fb, 0x1f3ff,),  # Emoji Modifier Fitzpatri..Emoji Modifier Fitzpatri
        ),
        'wider': (
        ),
    },
    'cmd.exe': {
        'narrower': (
            (0x1f3fb, 0x1f3ff,),  # Emoji Modifier Fitzpatri..Emoji Modifier Fitzpatri
        ),
        'wider': (
        ),
    },
    'foot': {
        'narrower': (
            (0x1f3fb, 0x1f3ff,),  # Emoji Modifier Fitzpatri..Emoji Modifier Fitzpatri
        ),
        'wider': (
        ),
    },
}
