"""
Exports WIDE_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file
_SET_F9137B07 = {
    'narrower': (
        (0x03030, 0x03030,),  # WAVY DASH
        (0x0303d, 0x0303d,),  # PART ALTERNATION MARK
        (0x03297, 0x03297,),  # CIRCLED IDEOGRAPH CONGRATULATION
        (0x03299, 0x03299,),  # CIRCLED IDEOGRAPH SECRET
        (0x1f202, 0x1f202,),  # SQUARED KATAKANA SA
        (0x1f237, 0x1f237,),  # SQUARED CJK UNIFIED IDEOGRAPH-6708
    ),
    'wider': (
    ),
}
_SET_E037CA5B = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x02ffc, 0x02fff,),  # IDEOGRAPHIC DESCRIPTION ..IDEOGRAPHIC DESCRIPTION
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x031ef, 0x031ef,),  # IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa89, 0x1fa8a,),  # HARP                    ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fabe, 0x1fabe,),  # LEAFLESS TREE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1fadc, 0x1fadc,),  # ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae9, 0x1faea,),  # FACE WITH BAGS UNDER EYE..(nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_CB203767 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x02ffc, 0x02fff,),  # IDEOGRAPHIC DESCRIPTION ..IDEOGRAPHIC DESCRIPTION
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x031ef, 0x031ef,),  # IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1f6dc, 0x1f6dc,),  # WIRELESS
        (0x1fa75, 0x1fa77,),  # LIGHT BLUE HEART        ..PINK HEART
        (0x1fa87, 0x1fa8a,),  # MARACAS                 ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1faad, 0x1faaf,),  # FOLDING HAND FAN        ..KHANDA
        (0x1fabb, 0x1fabf,),  # HYACINTH                ..GOOSE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facf,),  # (nil)                   ..DONKEY
        (0x1fada, 0x1fadc,),  # GINGER ROOT             ..ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae8, 0x1faea,),  # SHAKING FACE            ..(nil)
        (0x1faef, 0x1faef,),  # (nil)
        (0x1faf7, 0x1faf8,),  # LEFTWARDS PUSHING HAND  ..RIGHTWARDS PUSHING HAND
    ),
    'wider': (
    ),
}
_SET_4A2990AE = {
    'narrower': (
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa8a, 0x1fa8a,),  # (nil)
        (0x1fa8e, 0x1fa8e,),  # (nil)
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1faea, 0x1faea,),  # (nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_8073B7F9 = {
    'narrower': (
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
    ),
    'wider': (
    ),
}
_SET_22B651E0 = {
    'narrower': (
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f3fb, 0x1f3ff,),  # EMOJI MODIFIER FITZPATRI..EMOJI MODIFIER FITZPATRI
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa8a, 0x1fa8a,),  # (nil)
        (0x1fa8e, 0x1fa8e,),  # (nil)
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1faea, 0x1faea,),  # (nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_4009F7B8 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x02ffc, 0x02fff,),  # IDEOGRAPHIC DESCRIPTION ..IDEOGRAPHIC DESCRIPTION
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x031ef, 0x031ef,),  # IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa89, 0x1fa8a,),  # HARP                    ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fabe, 0x1fabe,),  # LEAFLESS TREE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1fadc, 0x1fadc,),  # ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae9, 0x1faea,),  # FACE WITH BAGS UNDER EYE..(nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_5432BD1F = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x0fa6e, 0x0fa6f,),  # (nil)
        (0x0fada, 0x0faff,),  # (nil)
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa89, 0x1fa8a,),  # HARP                    ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fabe, 0x1fabe,),  # LEAFLESS TREE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1fadc, 0x1fadc,),  # ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae9, 0x1faea,),  # FACE WITH BAGS UNDER EYE..(nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_4A0931DC = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f3fb, 0x1f3ff,),  # EMOJI MODIFIER FITZPATRI..EMOJI MODIFIER FITZPATRI
    ),
    'wider': (
    ),
}
_SET_18ADEFBE = {
    'narrower': (
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa8a, 0x1fa8a,),  # (nil)
        (0x1fa8e, 0x1fa8e,),  # (nil)
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1faea, 0x1faea,),  # (nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_3F19064D = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x02ffc, 0x02fff,),  # IDEOGRAPHIC DESCRIPTION ..IDEOGRAPHIC DESCRIPTION
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x031ef, 0x031ef,),  # IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION
    ),
    'wider': (
    ),
}
_SET_D6A1AAEF = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa89, 0x1fa8a,),  # HARP                    ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fabe, 0x1fabe,),  # LEAFLESS TREE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1fadc, 0x1fadc,),  # ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae9, 0x1faea,),  # FACE WITH BAGS UNDER EYE..(nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_A17C3EF2 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
    ),
    'wider': (
    ),
}
_SET_0F2EA143 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x0a960, 0x0a97c,),  # HANGUL CHOSEONG TIKEUT-M..HANGUL CHOSEONG SSANGYEO
        (0x16fe0, 0x16fe3,),  # TANGUT ITERATION MARK   ..OLD CHINESE ITERATION MA
        (0x1aff0, 0x1aff3,),  # KATAKANA LETTER MINNAN T..KATAKANA LETTER MINNAN T
        (0x1aff5, 0x1affb,),  # KATAKANA LETTER MINNAN T..KATAKANA LETTER MINNAN N
        (0x1affd, 0x1affe,),  # KATAKANA LETTER MINNAN N..KATAKANA LETTER MINNAN N
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f004, 0x1f004,),  # MAHJONG TILE RED DRAGON
        (0x1f0cf, 0x1f0cf,),  # PLAYING CARD BLACK JOKER
        (0x1f18e, 0x1f18e,),  # NEGATIVE SQUARED AB
        (0x1f191, 0x1f19a,),  # SQUARED CL              ..SQUARED VS
        (0x1f1e6, 0x1f202,),  # REGIONAL INDICATOR SYMBO..SQUARED KATAKANA SA
        (0x1f210, 0x1f23b,),  # SQUARED CJK UNIFIED IDEO..SQUARED CJK UNIFIED IDEO
        (0x1f240, 0x1f248,),  # TORTOISE SHELL BRACKETED..TORTOISE SHELL BRACKETED
        (0x1f250, 0x1f251,),  # CIRCLED IDEOGRAPH ADVANT..CIRCLED IDEOGRAPH ACCEPT
        (0x1f260, 0x1f265,),  # ROUNDED SYMBOL FOR FU   ..ROUNDED SYMBOL FOR CAI
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1f6dc, 0x1f6df,),  # WIRELESS                ..RING BUOY
        (0x1f7e0, 0x1f7eb,),  # LARGE ORANGE CIRCLE     ..LARGE BROWN SQUARE
        (0x1f7f0, 0x1f7f0,),  # HEAVY EQUALS SIGN
        (0x1f979, 0x1f979,),  # FACE HOLDING BACK TEARS
        (0x1f9cc, 0x1f9cc,),  # TROLL
        (0x1fa70, 0x1fa7c,),  # BALLET SHOES            ..CRUTCH
        (0x1fa80, 0x1fa8a,),  # YO-YO                   ..(nil)
        (0x1fa8e, 0x1fac6,),  # (nil)                   ..FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1fadc,),  # (nil)                   ..ROOT VEGETABLE
        (0x1fadf, 0x1faea,),  # SPLATTER                ..(nil)
        (0x1faef, 0x1faf8,),  # (nil)                   ..RIGHTWARDS PUSHING HAND
    ),
    'wider': (
    ),
}
_SET_BA5EAEA3 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x0fada, 0x0faff,),  # (nil)
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1f6dc, 0x1f6df,),  # WIRELESS                ..RING BUOY
        (0x1f7f0, 0x1f7f0,),  # HEAVY EQUALS SIGN
        (0x1fad7, 0x1fadc,),  # POURING LIQUID          ..ROOT VEGETABLE
        (0x1fadf, 0x1faea,),  # SPLATTER                ..(nil)
        (0x1faef, 0x1faf8,),  # (nil)                   ..RIGHTWARDS PUSHING HAND
    ),
    'wider': (
    ),
}
_SET_04D87E68 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x0fa6e, 0x0fa6f,),  # (nil)
        (0x0fada, 0x0faff,),  # (nil)
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f6d8, 0x1f6d8,),  # (nil)
        (0x1fa89, 0x1fa8a,),  # HARP                    ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fabe, 0x1fabe,),  # LEAFLESS TREE
        (0x1fac6, 0x1fac6,),  # FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1facd,),  # (nil)
        (0x1fadc, 0x1fadc,),  # ROOT VEGETABLE
        (0x1fadf, 0x1fadf,),  # SPLATTER
        (0x1fae9, 0x1faea,),  # FACE WITH BAGS UNDER EYE..(nil)
        (0x1faef, 0x1faef,),  # (nil)
    ),
    'wider': (
    ),
}
_SET_7A2BA5A5 = {
    'narrower': (
        (0x02630, 0x02637,),  # TRIGRAM FOR HEAVEN      ..TRIGRAM FOR EARTH
        (0x0268a, 0x0268f,),  # MONOGRAM FOR YANG       ..DIGRAM FOR GREATER YIN
        (0x02ffc, 0x02fff,),  # IDEOGRAPHIC DESCRIPTION ..IDEOGRAPHIC DESCRIPTION
        (0x031bb, 0x031bf,),  # BOPOMOFO FINAL LETTER G ..BOPOMOFO LETTER AH
        (0x031e4, 0x031e5,),  # CJK STROKE HXG          ..CJK STROKE SZP
        (0x031ef, 0x031ef,),  # IDEOGRAPHIC DESCRIPTION CHARACTER SUBTRACTION
        (0x04dc0, 0x04dff,),  # HEXAGRAM FOR THE CREATIV..HEXAGRAM FOR BEFORE COMP
        (0x1aff0, 0x1aff3,),  # KATAKANA LETTER MINNAN T..KATAKANA LETTER MINNAN T
        (0x1aff5, 0x1affb,),  # KATAKANA LETTER MINNAN T..KATAKANA LETTER MINNAN N
        (0x1affd, 0x1affe,),  # KATAKANA LETTER MINNAN N..KATAKANA LETTER MINNAN N
        (0x1d300, 0x1d356,),  # MONOGRAM FOR EARTH      ..TETRAGRAM FOR FOSTERING
        (0x1d360, 0x1d376,),  # COUNTING ROD UNIT DIGIT ..IDEOGRAPHIC TALLY MARK F
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
        (0x1f6d6, 0x1f6d8,),  # HUT                     ..(nil)
        (0x1f6dc, 0x1f6df,),  # WIRELESS                ..RING BUOY
        (0x1f6fb, 0x1f6fc,),  # PICKUP TRUCK            ..ROLLER SKATE
        (0x1f7f0, 0x1f7f0,),  # HEAVY EQUALS SIGN
        (0x1f90c, 0x1f90c,),  # PINCHED FINGERS
        (0x1f972, 0x1f972,),  # SMILING FACE WITH TEAR
        (0x1f977, 0x1f979,),  # NINJA                   ..FACE HOLDING BACK TEARS
        (0x1f9a3, 0x1f9a4,),  # MAMMOTH                 ..DODO
        (0x1f9ab, 0x1f9ad,),  # BEAVER                  ..SEAL
        (0x1f9cb, 0x1f9cc,),  # BUBBLE TEA              ..TROLL
        (0x1fa74, 0x1fa77,),  # THONG SANDAL            ..PINK HEART
        (0x1fa7b, 0x1fa7c,),  # X-RAY                   ..CRUTCH
        (0x1fa83, 0x1fa8a,),  # BOOMERANG               ..(nil)
        (0x1fa8e, 0x1fa8f,),  # (nil)                   ..SHOVEL
        (0x1fa96, 0x1fac6,),  # MILITARY HELMET         ..FINGERPRINT
        (0x1fac8, 0x1fac8,),  # (nil)
        (0x1facd, 0x1fadc,),  # (nil)                   ..ROOT VEGETABLE
        (0x1fadf, 0x1faea,),  # SPLATTER                ..(nil)
        (0x1faef, 0x1faf8,),  # (nil)                   ..RIGHTWARDS PUSHING HAND
    ),
    'wider': (
    ),
}


WIDE_OVERRIDES = {
    'bobcat': _SET_F9137B07,
    'conemu': _SET_E037CA5B,
    'extraterm': _SET_CB203767,
    'konsole': _SET_E037CA5B,
    'putty': _SET_CB203767,
    'rio': _SET_4A2990AE,
    'teraterm': _SET_8073B7F9,
    'terminal.app': _SET_4A2990AE,
    'terminal.exe': _SET_22B651E0,
    'vte': _SET_4009F7B8,
    'wezterm': _SET_4A2990AE,
    'xterm': _SET_5432BD1F,
    'zellij': _SET_4009F7B8,
    'cmd.exe': _SET_22B651E0,
    'foot': _SET_4A0931DC,
    'iterm2': _SET_18ADEFBE,
    'libvterm': _SET_18ADEFBE,
    'mintty': _SET_3F19064D,
    'mlterm': _SET_D6A1AAEF,
    'qtermwidget': _SET_A17C3EF2,
    'rxvt-unicode': _SET_5432BD1F,
    'screen': _SET_5432BD1F,
    'securecrt': _SET_0F2EA143,
    'st': _SET_5432BD1F,
    'terminology': _SET_BA5EAEA3,
    'tmux': _SET_04D87E68,
    'weston-terminal': _SET_5432BD1F,
    'xterm.js': _SET_7A2BA5A5,
    'zutty': _SET_5432BD1F,
}
