"""
Canonical terminal names and TERM_PROGRAM aliases.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file

KNOWN_TERMINALS = frozenset({
    'alacritty',
    'apple_terminal',
    'bobcat',
    'contour',
    'foot',
    'ghostty',
    'gnu screen',
    'iterm2',
    'kitty',
    'konsole',
    'libvterm',
    'mintty',
    'mlterm',
    'rio',
    'st-luke',
    'terminology',
    'tmux',
    'urxvt',
    'vte',
    'warp',
    'wezterm',
    'xterm',
    'xterm.js',
    'zellij',
})

TERM_PROGRAM_ALIASES = {
    'hyper': 'xterm.js',
    'iterm.app': 'iterm2',
    'rxvt': 'urxvt',
    'tabby': 'xterm.js',
    'vscode': 'xterm.js',
    'warpterminal': 'warp',
}

TERM_ALIASES = {
    'rxvt-unicode-256color': 'urxvt',
    'screen': 'gnu screen',
    'st-256color': 'st-luke',
    'tmux-256color': 'tmux',
    'xterm-ghostty': 'ghostty',
    'xterm-kitty': 'kitty',
}
