"""
Exports SRI_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: disable=duplicate-code
_SET_8073b7f9 = {
    'narrower': (
        (0x1f1e6, 0x1f1ff,),  # REGIONAL INDICATOR SYMBO..REGIONAL INDICATOR SYMBO
    ),
    'wider': (
    ),
}


SRI_OVERRIDES = {
    'extraterm': _SET_8073b7f9,
    'putty': _SET_8073b7f9,
    'rio': _SET_8073b7f9,
    'teraterm': _SET_8073b7f9,
    'terminal.app': _SET_8073b7f9,
    'terminal.exe': _SET_8073b7f9,
    'vte': _SET_8073b7f9,
    'wezterm': _SET_8073b7f9,
    'xterm': _SET_8073b7f9,
    'zellij': _SET_8073b7f9,
    'alacritty': _SET_8073b7f9,
    'cmd.exe': _SET_8073b7f9,
    'foot': _SET_8073b7f9,
    'mlterm': _SET_8073b7f9,
    'qtermwidget': _SET_8073b7f9,
    'rxvt-unicode': _SET_8073b7f9,
    'screen': _SET_8073b7f9,
    'securecrt': _SET_8073b7f9,
    'st': _SET_8073b7f9,
    'terminology': _SET_8073b7f9,
    'weston-terminal': _SET_8073b7f9,
    'xterm.js': _SET_8073b7f9,
    'zutty': _SET_8073b7f9,
}
