"""
Exports VS16_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file
_SET_92876801 = {
    'narrower': (
    ),
    'wider': (
        (0x1f170, 0x1f171,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
        (0x1f17e, 0x1f17f,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
    ),
}
_SET_67F306EA = {
    'narrower': (
        (0x00023, 0x00023,),  # NUMBER SIGN
        (0x0002a, 0x0002a,),  # ASTERISK
        (0x00030, 0x00039,),  # DIGIT ZERO              ..DIGIT NINE
        (0x000a9, 0x000a9,),  # COPYRIGHT SIGN
        (0x000ae, 0x000ae,),  # REGISTERED SIGN
        (0x0203c, 0x0203c,),  # DOUBLE EXCLAMATION MARK
        (0x02049, 0x02049,),  # EXCLAMATION QUESTION MARK
        (0x02122, 0x02122,),  # TRADE MARK SIGN
        (0x02139, 0x02139,),  # INFORMATION SOURCE
        (0x02194, 0x02199,),  # LEFT RIGHT ARROW        ..SOUTH WEST ARROW
        (0x021a9, 0x021aa,),  # LEFTWARDS ARROW WITH HOO..RIGHTWARDS ARROW WITH HO
        (0x02328, 0x02328,),  # KEYBOARD
        (0x023cf, 0x023cf,),  # EJECT SYMBOL
        (0x023ed, 0x023ef,),  # BLACK RIGHT-POINTING DOU..BLACK RIGHT-POINTING TRI
        (0x023f1, 0x023f2,),  # STOPWATCH               ..TIMER CLOCK
        (0x023f8, 0x023fa,),  # DOUBLE VERTICAL BAR     ..BLACK CIRCLE FOR RECORD
        (0x024c2, 0x024c2,),  # CIRCLED LATIN CAPITAL LETTER M
        (0x025aa, 0x025ab,),  # BLACK SMALL SQUARE      ..WHITE SMALL SQUARE
        (0x025b6, 0x025b6,),  # BLACK RIGHT-POINTING TRIANGLE
        (0x025c0, 0x025c0,),  # BLACK LEFT-POINTING TRIANGLE
        (0x025fb, 0x025fc,),  # WHITE MEDIUM SQUARE     ..BLACK MEDIUM SQUARE
        (0x02600, 0x02604,),  # BLACK SUN WITH RAYS     ..COMET
        (0x0260e, 0x0260e,),  # BLACK TELEPHONE
        (0x02611, 0x02611,),  # BALLOT BOX WITH CHECK
        (0x02618, 0x02618,),  # SHAMROCK
        (0x0261d, 0x0261d,),  # WHITE UP POINTING INDEX
        (0x02620, 0x02620,),  # SKULL AND CROSSBONES
        (0x02622, 0x02623,),  # RADIOACTIVE SIGN        ..BIOHAZARD SIGN
        (0x02626, 0x02626,),  # ORTHODOX CROSS
        (0x0262a, 0x0262a,),  # STAR AND CRESCENT
        (0x0262e, 0x0262f,),  # PEACE SYMBOL            ..YIN YANG
        (0x02638, 0x0263a,),  # WHEEL OF DHARMA         ..WHITE SMILING FACE
        (0x02640, 0x02640,),  # FEMALE SIGN
        (0x02642, 0x02642,),  # MALE SIGN
        (0x0265f, 0x02660,),  # BLACK CHESS PAWN        ..BLACK SPADE SUIT
        (0x02663, 0x02663,),  # BLACK CLUB SUIT
        (0x02665, 0x02666,),  # BLACK HEART SUIT        ..BLACK DIAMOND SUIT
        (0x02668, 0x02668,),  # HOT SPRINGS
        (0x0267b, 0x0267b,),  # BLACK UNIVERSAL RECYCLING SYMBOL
        (0x0267e, 0x0267e,),  # PERMANENT PAPER SIGN
        (0x02692, 0x02692,),  # HAMMER AND PICK
        (0x02694, 0x02697,),  # CROSSED SWORDS          ..ALEMBIC
        (0x02699, 0x02699,),  # GEAR
        (0x0269b, 0x0269c,),  # ATOM SYMBOL             ..FLEUR-DE-LIS
        (0x026a0, 0x026a0,),  # WARNING SIGN
        (0x026a7, 0x026a7,),  # MALE WITH STROKE AND MALE AND FEMALE SIGN
        (0x026b0, 0x026b1,),  # COFFIN                  ..FUNERAL URN
        (0x026c8, 0x026c8,),  # THUNDER CLOUD AND RAIN
        (0x026cf, 0x026cf,),  # PICK
        (0x026d1, 0x026d1,),  # HELMET WITH WHITE CROSS
        (0x026d3, 0x026d3,),  # CHAINS
        (0x026e9, 0x026e9,),  # SHINTO SHRINE
        (0x026f0, 0x026f1,),  # MOUNTAIN                ..UMBRELLA ON GROUND
        (0x026f4, 0x026f4,),  # FERRY
        (0x026f7, 0x026f9,),  # SKIER                   ..PERSON WITH BALL
        (0x02702, 0x02702,),  # BLACK SCISSORS
        (0x02708, 0x02709,),  # AIRPLANE                ..ENVELOPE
        (0x0270c, 0x0270d,),  # VICTORY HAND            ..WRITING HAND
        (0x0270f, 0x0270f,),  # PENCIL
        (0x02712, 0x02712,),  # BLACK NIB
        (0x02714, 0x02714,),  # HEAVY CHECK MARK
        (0x02716, 0x02716,),  # HEAVY MULTIPLICATION X
        (0x0271d, 0x0271d,),  # LATIN CROSS
        (0x02721, 0x02721,),  # STAR OF DAVID
        (0x02733, 0x02734,),  # EIGHT SPOKED ASTERISK   ..EIGHT POINTED BLACK STAR
        (0x02744, 0x02744,),  # SNOWFLAKE
        (0x02747, 0x02747,),  # SPARKLE
        (0x02763, 0x02764,),  # HEAVY HEART EXCLAMATION ..HEAVY BLACK HEART
        (0x027a1, 0x027a1,),  # BLACK RIGHTWARDS ARROW
        (0x02934, 0x02935,),  # ARROW POINTING RIGHTWARD..ARROW POINTING RIGHTWARD
        (0x02b05, 0x02b07,),  # LEFTWARDS BLACK ARROW   ..DOWNWARDS BLACK ARROW
        (0x1f170, 0x1f171,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
        (0x1f17e, 0x1f17f,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
        (0x1f321, 0x1f321,),  # THERMOMETER
        (0x1f324, 0x1f32c,),  # WHITE SUN WITH SMALL CLO..WIND BLOWING FACE
        (0x1f336, 0x1f336,),  # HOT PEPPER
        (0x1f37d, 0x1f37d,),  # FORK AND KNIFE WITH PLATE
        (0x1f396, 0x1f397,),  # MILITARY MEDAL          ..REMINDER RIBBON
        (0x1f399, 0x1f39b,),  # STUDIO MICROPHONE       ..CONTROL KNOBS
        (0x1f39e, 0x1f39f,),  # FILM FRAMES             ..ADMISSION TICKETS
        (0x1f3cb, 0x1f3ce,),  # WEIGHT LIFTER           ..RACING CAR
        (0x1f3d4, 0x1f3df,),  # SNOW CAPPED MOUNTAIN    ..STADIUM
        (0x1f3f3, 0x1f3f3,),  # WAVING WHITE FLAG
        (0x1f3f5, 0x1f3f5,),  # ROSETTE
        (0x1f3f7, 0x1f3f7,),  # LABEL
        (0x1f43f, 0x1f43f,),  # CHIPMUNK
        (0x1f441, 0x1f441,),  # EYE
        (0x1f4fd, 0x1f4fd,),  # FILM PROJECTOR
        (0x1f549, 0x1f54a,),  # OM SYMBOL               ..DOVE OF PEACE
        (0x1f56f, 0x1f570,),  # CANDLE                  ..MANTELPIECE CLOCK
        (0x1f573, 0x1f579,),  # HOLE                    ..JOYSTICK
        (0x1f587, 0x1f587,),  # LINKED PAPERCLIPS
        (0x1f58a, 0x1f58d,),  # LOWER LEFT BALLPOINT PEN..LOWER LEFT CRAYON
        (0x1f590, 0x1f590,),  # RAISED HAND WITH FINGERS SPLAYED
        (0x1f5a5, 0x1f5a5,),  # DESKTOP COMPUTER
        (0x1f5a8, 0x1f5a8,),  # PRINTER
        (0x1f5b1, 0x1f5b2,),  # THREE BUTTON MOUSE      ..TRACKBALL
        (0x1f5bc, 0x1f5bc,),  # FRAME WITH PICTURE
        (0x1f5c2, 0x1f5c4,),  # CARD INDEX DIVIDERS     ..FILE CABINET
        (0x1f5d1, 0x1f5d3,),  # WASTEBASKET             ..SPIRAL CALENDAR PAD
        (0x1f5dc, 0x1f5de,),  # COMPRESSION             ..ROLLED-UP NEWSPAPER
        (0x1f5e1, 0x1f5e1,),  # DAGGER KNIFE
        (0x1f5e3, 0x1f5e3,),  # SPEAKING HEAD IN SILHOUETTE
        (0x1f5e8, 0x1f5e8,),  # LEFT SPEECH BUBBLE
        (0x1f5ef, 0x1f5ef,),  # RIGHT ANGER BUBBLE
        (0x1f5f3, 0x1f5f3,),  # BALLOT BOX WITH BALLOT
        (0x1f5fa, 0x1f5fa,),  # WORLD MAP
        (0x1f6cb, 0x1f6cb,),  # COUCH AND LAMP
        (0x1f6cd, 0x1f6cf,),  # SHOPPING BAGS           ..BED
        (0x1f6e0, 0x1f6e5,),  # HAMMER AND WRENCH       ..MOTOR BOAT
        (0x1f6e9, 0x1f6e9,),  # SMALL AIRPLANE
        (0x1f6f0, 0x1f6f0,),  # SATELLITE
        (0x1f6f3, 0x1f6f3,),  # PASSENGER SHIP
    ),
    'wider': (
    ),
}
_SET_F2FBD34E = {
    'narrower': (
        (0x00023, 0x00023,),  # NUMBER SIGN
        (0x0002a, 0x0002a,),  # ASTERISK
        (0x00030, 0x00039,),  # DIGIT ZERO              ..DIGIT NINE
    ),
    'wider': (
    ),
}
_SET_02F4B9FD = {
    'narrower': (
    ),
    'wider': (
        (0x0261d, 0x0261d,),  # WHITE UP POINTING INDEX
        (0x026f9, 0x026f9,),  # PERSON WITH BALL
        (0x0270c, 0x0270d,),  # VICTORY HAND            ..WRITING HAND
        (0x1f3cb, 0x1f3cc,),  # WEIGHT LIFTER           ..GOLFER
        (0x1f574, 0x1f575,),  # MAN IN BUSINESS SUIT LEV..SLEUTH OR SPY
        (0x1f590, 0x1f590,),  # RAISED HAND WITH FINGERS SPLAYED
    ),
}
_SET_9DEBD3CE = {
    'narrower': (
        (0x00023, 0x00023,),  # NUMBER SIGN
        (0x0002a, 0x0002a,),  # ASTERISK
        (0x00030, 0x00039,),  # DIGIT ZERO              ..DIGIT NINE
        (0x000a9, 0x000a9,),  # COPYRIGHT SIGN
        (0x000ae, 0x000ae,),  # REGISTERED SIGN
        (0x0203c, 0x0203c,),  # DOUBLE EXCLAMATION MARK
        (0x02049, 0x02049,),  # EXCLAMATION QUESTION MARK
        (0x02122, 0x02122,),  # TRADE MARK SIGN
        (0x02139, 0x02139,),  # INFORMATION SOURCE
        (0x02194, 0x02199,),  # LEFT RIGHT ARROW        ..SOUTH WEST ARROW
        (0x021a9, 0x021aa,),  # LEFTWARDS ARROW WITH HOO..RIGHTWARDS ARROW WITH HO
        (0x02328, 0x02328,),  # KEYBOARD
        (0x023cf, 0x023cf,),  # EJECT SYMBOL
        (0x025aa, 0x025ab,),  # BLACK SMALL SQUARE      ..WHITE SMALL SQUARE
        (0x025b6, 0x025b6,),  # BLACK RIGHT-POINTING TRIANGLE
        (0x025c0, 0x025c0,),  # BLACK LEFT-POINTING TRIANGLE
        (0x025fb, 0x025fc,),  # WHITE MEDIUM SQUARE     ..BLACK MEDIUM SQUARE
        (0x02600, 0x02604,),  # BLACK SUN WITH RAYS     ..COMET
        (0x0260e, 0x0260e,),  # BLACK TELEPHONE
        (0x02611, 0x02611,),  # BALLOT BOX WITH CHECK
        (0x02618, 0x02618,),  # SHAMROCK
        (0x02620, 0x02620,),  # SKULL AND CROSSBONES
        (0x02622, 0x02623,),  # RADIOACTIVE SIGN        ..BIOHAZARD SIGN
        (0x02626, 0x02626,),  # ORTHODOX CROSS
        (0x0262a, 0x0262a,),  # STAR AND CRESCENT
        (0x0262e, 0x0262f,),  # PEACE SYMBOL            ..YIN YANG
        (0x02638, 0x0263a,),  # WHEEL OF DHARMA         ..WHITE SMILING FACE
        (0x02640, 0x02640,),  # FEMALE SIGN
        (0x02642, 0x02642,),  # MALE SIGN
        (0x0265f, 0x02660,),  # BLACK CHESS PAWN        ..BLACK SPADE SUIT
        (0x02663, 0x02663,),  # BLACK CLUB SUIT
        (0x02665, 0x02666,),  # BLACK HEART SUIT        ..BLACK DIAMOND SUIT
        (0x02668, 0x02668,),  # HOT SPRINGS
        (0x0267b, 0x0267b,),  # BLACK UNIVERSAL RECYCLING SYMBOL
        (0x0267e, 0x0267e,),  # PERMANENT PAPER SIGN
        (0x02692, 0x02692,),  # HAMMER AND PICK
        (0x02694, 0x02697,),  # CROSSED SWORDS          ..ALEMBIC
        (0x02699, 0x02699,),  # GEAR
        (0x0269b, 0x0269c,),  # ATOM SYMBOL             ..FLEUR-DE-LIS
        (0x026a0, 0x026a0,),  # WARNING SIGN
        (0x026a7, 0x026a7,),  # MALE WITH STROKE AND MALE AND FEMALE SIGN
        (0x026b0, 0x026b1,),  # COFFIN                  ..FUNERAL URN
        (0x026f4, 0x026f4,),  # FERRY
        (0x02702, 0x02702,),  # BLACK SCISSORS
        (0x02708, 0x02709,),  # AIRPLANE                ..ENVELOPE
        (0x0270f, 0x0270f,),  # PENCIL
        (0x02712, 0x02712,),  # BLACK NIB
        (0x02714, 0x02714,),  # HEAVY CHECK MARK
        (0x02716, 0x02716,),  # HEAVY MULTIPLICATION X
        (0x0271d, 0x0271d,),  # LATIN CROSS
        (0x02721, 0x02721,),  # STAR OF DAVID
        (0x02733, 0x02734,),  # EIGHT SPOKED ASTERISK   ..EIGHT POINTED BLACK STAR
        (0x02744, 0x02744,),  # SNOWFLAKE
        (0x02747, 0x02747,),  # SPARKLE
        (0x02763, 0x02764,),  # HEAVY HEART EXCLAMATION ..HEAVY BLACK HEART
        (0x027a1, 0x027a1,),  # BLACK RIGHTWARDS ARROW
        (0x02b05, 0x02b07,),  # LEFTWARDS BLACK ARROW   ..DOWNWARDS BLACK ARROW
    ),
    'wider': (
        (0x023ed, 0x023ef,),  # BLACK RIGHT-POINTING DOU..BLACK RIGHT-POINTING TRI
        (0x023f1, 0x023f2,),  # STOPWATCH               ..TIMER CLOCK
        (0x023f8, 0x023fa,),  # DOUBLE VERTICAL BAR     ..BLACK CIRCLE FOR RECORD
        (0x024c2, 0x024c2,),  # CIRCLED LATIN CAPITAL LETTER M
        (0x0261d, 0x0261d,),  # WHITE UP POINTING INDEX
        (0x026c8, 0x026c8,),  # THUNDER CLOUD AND RAIN
        (0x026cf, 0x026cf,),  # PICK
        (0x026d1, 0x026d1,),  # HELMET WITH WHITE CROSS
        (0x026d3, 0x026d3,),  # CHAINS
        (0x026e9, 0x026e9,),  # SHINTO SHRINE
        (0x026f0, 0x026f1,),  # MOUNTAIN                ..UMBRELLA ON GROUND
        (0x026f7, 0x026f9,),  # SKIER                   ..PERSON WITH BALL
        (0x0270c, 0x0270d,),  # VICTORY HAND            ..WRITING HAND
        (0x02934, 0x02935,),  # ARROW POINTING RIGHTWARD..ARROW POINTING RIGHTWARD
        (0x1f170, 0x1f171,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
        (0x1f17e, 0x1f17f,),  # NEGATIVE SQUARED LATIN C..NEGATIVE SQUARED LATIN C
        (0x1f321, 0x1f321,),  # THERMOMETER
        (0x1f324, 0x1f32c,),  # WHITE SUN WITH SMALL CLO..WIND BLOWING FACE
        (0x1f336, 0x1f336,),  # HOT PEPPER
        (0x1f37d, 0x1f37d,),  # FORK AND KNIFE WITH PLATE
        (0x1f396, 0x1f397,),  # MILITARY MEDAL          ..REMINDER RIBBON
        (0x1f399, 0x1f39b,),  # STUDIO MICROPHONE       ..CONTROL KNOBS
        (0x1f39e, 0x1f39f,),  # FILM FRAMES             ..ADMISSION TICKETS
        (0x1f3cb, 0x1f3ce,),  # WEIGHT LIFTER           ..RACING CAR
        (0x1f3d4, 0x1f3df,),  # SNOW CAPPED MOUNTAIN    ..STADIUM
        (0x1f3f3, 0x1f3f3,),  # WAVING WHITE FLAG
        (0x1f3f5, 0x1f3f5,),  # ROSETTE
        (0x1f3f7, 0x1f3f7,),  # LABEL
        (0x1f43f, 0x1f43f,),  # CHIPMUNK
        (0x1f441, 0x1f441,),  # EYE
        (0x1f4fd, 0x1f4fd,),  # FILM PROJECTOR
        (0x1f549, 0x1f54a,),  # OM SYMBOL               ..DOVE OF PEACE
        (0x1f56f, 0x1f570,),  # CANDLE                  ..MANTELPIECE CLOCK
        (0x1f573, 0x1f579,),  # HOLE                    ..JOYSTICK
        (0x1f587, 0x1f587,),  # LINKED PAPERCLIPS
        (0x1f58a, 0x1f58d,),  # LOWER LEFT BALLPOINT PEN..LOWER LEFT CRAYON
        (0x1f590, 0x1f590,),  # RAISED HAND WITH FINGERS SPLAYED
        (0x1f5a5, 0x1f5a5,),  # DESKTOP COMPUTER
        (0x1f5a8, 0x1f5a8,),  # PRINTER
        (0x1f5b1, 0x1f5b2,),  # THREE BUTTON MOUSE      ..TRACKBALL
        (0x1f5bc, 0x1f5bc,),  # FRAME WITH PICTURE
        (0x1f5c2, 0x1f5c4,),  # CARD INDEX DIVIDERS     ..FILE CABINET
        (0x1f5d1, 0x1f5d3,),  # WASTEBASKET             ..SPIRAL CALENDAR PAD
        (0x1f5dc, 0x1f5de,),  # COMPRESSION             ..ROLLED-UP NEWSPAPER
        (0x1f5e1, 0x1f5e1,),  # DAGGER KNIFE
        (0x1f5e3, 0x1f5e3,),  # SPEAKING HEAD IN SILHOUETTE
        (0x1f5e8, 0x1f5e8,),  # LEFT SPEECH BUBBLE
        (0x1f5ef, 0x1f5ef,),  # RIGHT ANGER BUBBLE
        (0x1f5f3, 0x1f5f3,),  # BALLOT BOX WITH BALLOT
        (0x1f5fa, 0x1f5fa,),  # WORLD MAP
        (0x1f6cb, 0x1f6cb,),  # COUCH AND LAMP
        (0x1f6cd, 0x1f6cf,),  # SHOPPING BAGS           ..BED
        (0x1f6e0, 0x1f6e5,),  # HAMMER AND WRENCH       ..MOTOR BOAT
        (0x1f6e9, 0x1f6e9,),  # SMALL AIRPLANE
        (0x1f6f0, 0x1f6f0,),  # SATELLITE
        (0x1f6f3, 0x1f6f3,),  # PASSENGER SHIP
    ),
}


VS16_OVERRIDES = {
    'conemu': _SET_92876801,
    'putty': _SET_67F306EA,
    'rio': _SET_67F306EA,
    'teraterm': _SET_67F306EA,
    'terminal.app': _SET_67F306EA,
    'vte': _SET_67F306EA,
    'wezterm': _SET_67F306EA,
    'xterm': _SET_67F306EA,
    'zellij': _SET_67F306EA,
    'alacritty': _SET_67F306EA,
    'contour': _SET_67F306EA,
    'iterm2': _SET_F2FBD34E,
    'kitty': _SET_02F4B9FD,
    'libvterm': _SET_9DEBD3CE,
    'mlterm': _SET_67F306EA,
    'qtermwidget': _SET_67F306EA,
    'rxvt-unicode': _SET_67F306EA,
    'screen': _SET_67F306EA,
    'securecrt': _SET_67F306EA,
    'st': _SET_67F306EA,
    'terminology': _SET_67F306EA,
    'tmux': _SET_02F4B9FD,
    'xterm.js': _SET_67F306EA,
    'zutty': _SET_67F306EA,
}
