"""
Canonical terminal names and TERM_PROGRAM/TERM aliases.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file

KNOWN_TERMINALS = frozenset({
    'absolutetelnet/ssh',
    'alacritty',
    'bobcat',
    'cmd.exe',
    'conemu',
    'contour',
    'extraterm',
    'foot',
    'ghostty',
    'iterm2',
    'kitty',
    'konsole',
    'libvterm',
    'linux fbdev',
    'mintty',
    'mlterm',
    'putty',
    'qtermwidget',
    'rio',
    'rxvt-unicode',
    'screen',
    'securecrt',
    'st',
    'syncterm',
    'teraterm',
    'terminal.app',
    'terminal.exe',
    'terminology',
    'tmux',
    'vte',
    'weston-terminal',
    'wezterm',
    'xterm',
    'xterm.js',
    'zellij',
    'zutty',
})

TERM_PROGRAM_ALIASES = {
    'apple_terminal': 'terminal.app',
    'hyper': 'xterm.js',
    'iterm': 'iterm2',
    'iterm.app': 'iterm2',
    'rxvt': 'rxvt-unicode',
    'tabby': 'xterm.js',
    'urxvt': 'rxvt-unicode',
    'vscode': 'xterm.js',
}

TERM_ALIASES = {
    'rxvt-unicode-256color': 'rxvt-unicode',
    'st-256color': 'st',
    'tmux-256color': 'tmux',
    'xterm-ghostty': 'ghostty',
    'xterm-kitty': 'kitty',
}
