"""
Exports VS15_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: disable=duplicate-code
_SET_cdb8c790 = {
    'narrower': (
    ),
    'wider': (
        (0x03030, 0x03030,),  # WAVY DASH
        (0x0303d, 0x0303d,),  # PART ALTERNATION MARK
        (0x03297, 0x03297,),  # CIRCLED IDEOGRAPH CONGRATULATION
        (0x03299, 0x03299,),  # CIRCLED IDEOGRAPH SECRET
        (0x1f202, 0x1f202,),  # SQUARED KATAKANA SA
        (0x1f237, 0x1f237,),  # SQUARED CJK UNIFIED IDEOGRAPH-6708
    ),
}
_SET_c137548c = {
    'narrower': (
    ),
    'wider': (
        (0x0231a, 0x0231b,),  # WATCH                   ..HOURGLASS
        (0x023e9, 0x023ec,),  # BLACK RIGHT-POINTING DOU..BLACK DOWN-POINTING DOUB
        (0x023f0, 0x023f0,),  # ALARM CLOCK
        (0x023f3, 0x023f3,),  # HOURGLASS WITH FLOWING SAND
        (0x025fd, 0x025fe,),  # WHITE MEDIUM SMALL SQUAR..BLACK MEDIUM SMALL SQUAR
        (0x02614, 0x02615,),  # UMBRELLA WITH RAIN DROPS..HOT BEVERAGE
        (0x02648, 0x02653,),  # ARIES                   ..PISCES
        (0x0267f, 0x0267f,),  # WHEELCHAIR SYMBOL
        (0x02693, 0x02693,),  # ANCHOR
        (0x026a1, 0x026a1,),  # HIGH VOLTAGE SIGN
        (0x026aa, 0x026ab,),  # MEDIUM WHITE CIRCLE     ..MEDIUM BLACK CIRCLE
        (0x026bd, 0x026be,),  # SOCCER BALL             ..BASEBALL
        (0x026c4, 0x026c5,),  # SNOWMAN WITHOUT SNOW    ..SUN BEHIND CLOUD
        (0x026ce, 0x026ce,),  # OPHIUCHUS
        (0x026d4, 0x026d4,),  # NO ENTRY
        (0x026ea, 0x026ea,),  # CHURCH
        (0x026f2, 0x026f3,),  # FOUNTAIN                ..FLAG IN HOLE
        (0x026f5, 0x026f5,),  # SAILBOAT
        (0x026fa, 0x026fa,),  # TENT
        (0x026fd, 0x026fd,),  # FUEL PUMP
        (0x02705, 0x02705,),  # WHITE HEAVY CHECK MARK
        (0x0270a, 0x0270b,),  # RAISED FIST             ..RAISED HAND
        (0x02728, 0x02728,),  # SPARKLES
        (0x0274c, 0x0274c,),  # CROSS MARK
        (0x0274e, 0x0274e,),  # NEGATIVE SQUARED CROSS MARK
        (0x02753, 0x02755,),  # BLACK QUESTION MARK ORNA..WHITE EXCLAMATION MARK O
        (0x02757, 0x02757,),  # HEAVY EXCLAMATION MARK SYMBOL
        (0x02795, 0x02797,),  # HEAVY PLUS SIGN         ..HEAVY DIVISION SIGN
        (0x027b0, 0x027b0,),  # CURLY LOOP
        (0x027bf, 0x027bf,),  # DOUBLE CURLY LOOP
        (0x02b1b, 0x02b1c,),  # BLACK LARGE SQUARE      ..WHITE LARGE SQUARE
        (0x02b50, 0x02b50,),  # WHITE MEDIUM STAR
        (0x02b55, 0x02b55,),  # HEAVY LARGE CIRCLE
        (0x03030, 0x03030,),  # WAVY DASH
        (0x0303d, 0x0303d,),  # PART ALTERNATION MARK
        (0x03297, 0x03297,),  # CIRCLED IDEOGRAPH CONGRATULATION
        (0x03299, 0x03299,),  # CIRCLED IDEOGRAPH SECRET
        (0x1f004, 0x1f004,),  # MAHJONG TILE RED DRAGON
        (0x1f202, 0x1f202,),  # SQUARED KATAKANA SA
        (0x1f21a, 0x1f21a,),  # SQUARED CJK UNIFIED IDEOGRAPH-7121
        (0x1f22f, 0x1f22f,),  # SQUARED CJK UNIFIED IDEOGRAPH-6307
        (0x1f237, 0x1f237,),  # SQUARED CJK UNIFIED IDEOGRAPH-6708
        (0x1f30d, 0x1f30f,),  # EARTH GLOBE EUROPE-AFRIC..EARTH GLOBE ASIA-AUSTRAL
        (0x1f315, 0x1f315,),  # FULL MOON SYMBOL
        (0x1f31c, 0x1f31c,),  # LAST QUARTER MOON WITH FACE
        (0x1f378, 0x1f378,),  # COCKTAIL GLASS
        (0x1f393, 0x1f393,),  # GRADUATION CAP
        (0x1f3a7, 0x1f3a7,),  # HEADPHONE
        (0x1f3ac, 0x1f3ae,),  # CLAPPER BOARD           ..VIDEO GAME
        (0x1f3c2, 0x1f3c2,),  # SNOWBOARDER
        (0x1f3c4, 0x1f3c4,),  # SURFER
        (0x1f3c6, 0x1f3c6,),  # TROPHY
        (0x1f3ca, 0x1f3ca,),  # SWIMMER
        (0x1f3e0, 0x1f3e0,),  # HOUSE BUILDING
        (0x1f3ed, 0x1f3ed,),  # FACTORY
        (0x1f408, 0x1f408,),  # CAT
        (0x1f415, 0x1f415,),  # DOG
        (0x1f41f, 0x1f41f,),  # FISH
        (0x1f426, 0x1f426,),  # BIRD
        (0x1f442, 0x1f442,),  # EAR
        (0x1f446, 0x1f449,),  # WHITE UP POINTING BACKHA..WHITE RIGHT POINTING BAC
        (0x1f44d, 0x1f44e,),  # THUMBS UP SIGN          ..THUMBS DOWN SIGN
        (0x1f453, 0x1f453,),  # EYEGLASSES
        (0x1f46a, 0x1f46a,),  # FAMILY
        (0x1f47d, 0x1f47d,),  # EXTRATERRESTRIAL ALIEN
        (0x1f4a3, 0x1f4a3,),  # BOMB
        (0x1f4b0, 0x1f4b0,),  # MONEY BAG
        (0x1f4b3, 0x1f4b3,),  # CREDIT CARD
        (0x1f4bb, 0x1f4bb,),  # PERSONAL COMPUTER
        (0x1f4bf, 0x1f4bf,),  # OPTICAL DISC
        (0x1f4cb, 0x1f4cb,),  # CLIPBOARD
        (0x1f4da, 0x1f4da,),  # BOOKS
        (0x1f4df, 0x1f4df,),  # PAGER
        (0x1f4e4, 0x1f4e6,),  # OUTBOX TRAY             ..PACKAGE
        (0x1f4ea, 0x1f4ed,),  # CLOSED MAILBOX WITH LOWE..OPEN MAILBOX WITH LOWERE
        (0x1f4f7, 0x1f4f7,),  # CAMERA
        (0x1f4f9, 0x1f4fb,),  # VIDEO CAMERA            ..RADIO
        (0x1f508, 0x1f508,),  # SPEAKER
        (0x1f50d, 0x1f50d,),  # LEFT-POINTING MAGNIFYING GLASS
        (0x1f512, 0x1f513,),  # LOCK                    ..OPEN LOCK
        (0x1f550, 0x1f567,),  # CLOCK FACE ONE OCLOCK   ..CLOCK FACE TWELVE-THIRTY
        (0x1f610, 0x1f610,),  # NEUTRAL FACE
        (0x1f687, 0x1f687,),  # METRO
        (0x1f68d, 0x1f68d,),  # ONCOMING BUS
        (0x1f691, 0x1f691,),  # AMBULANCE
        (0x1f694, 0x1f694,),  # ONCOMING POLICE CAR
        (0x1f698, 0x1f698,),  # ONCOMING AUTOMOBILE
        (0x1f6ad, 0x1f6ad,),  # NO SMOKING SYMBOL
        (0x1f6b2, 0x1f6b2,),  # BICYCLE
        (0x1f6b9, 0x1f6ba,),  # MENS SYMBOL             ..WOMENS SYMBOL
        (0x1f6bc, 0x1f6bc,),  # BABY SYMBOL
    ),
}
_SET_b708b91e = {
    'narrower': (
    ),
    'wider': (
        (0x0231a, 0x0231b,),  # WATCH                   ..HOURGLASS
        (0x023e9, 0x023ec,),  # BLACK RIGHT-POINTING DOU..BLACK DOWN-POINTING DOUB
        (0x023f0, 0x023f0,),  # ALARM CLOCK
        (0x023f3, 0x023f3,),  # HOURGLASS WITH FLOWING SAND
        (0x025fd, 0x025fe,),  # WHITE MEDIUM SMALL SQUAR..BLACK MEDIUM SMALL SQUAR
        (0x02614, 0x02615,),  # UMBRELLA WITH RAIN DROPS..HOT BEVERAGE
        (0x02648, 0x02653,),  # ARIES                   ..PISCES
        (0x0267f, 0x0267f,),  # WHEELCHAIR SYMBOL
        (0x02693, 0x02693,),  # ANCHOR
        (0x026a1, 0x026a1,),  # HIGH VOLTAGE SIGN
        (0x026aa, 0x026ab,),  # MEDIUM WHITE CIRCLE     ..MEDIUM BLACK CIRCLE
        (0x026bd, 0x026be,),  # SOCCER BALL             ..BASEBALL
        (0x026c4, 0x026c5,),  # SNOWMAN WITHOUT SNOW    ..SUN BEHIND CLOUD
        (0x026ce, 0x026ce,),  # OPHIUCHUS
        (0x026d4, 0x026d4,),  # NO ENTRY
        (0x026ea, 0x026ea,),  # CHURCH
        (0x026f2, 0x026f3,),  # FOUNTAIN                ..FLAG IN HOLE
        (0x026f5, 0x026f5,),  # SAILBOAT
        (0x026fa, 0x026fa,),  # TENT
        (0x026fd, 0x026fd,),  # FUEL PUMP
        (0x02705, 0x02705,),  # WHITE HEAVY CHECK MARK
        (0x0270a, 0x0270b,),  # RAISED FIST             ..RAISED HAND
        (0x02728, 0x02728,),  # SPARKLES
        (0x0274c, 0x0274c,),  # CROSS MARK
        (0x0274e, 0x0274e,),  # NEGATIVE SQUARED CROSS MARK
        (0x02753, 0x02755,),  # BLACK QUESTION MARK ORNA..WHITE EXCLAMATION MARK O
        (0x02757, 0x02757,),  # HEAVY EXCLAMATION MARK SYMBOL
        (0x02795, 0x02797,),  # HEAVY PLUS SIGN         ..HEAVY DIVISION SIGN
        (0x027b0, 0x027b0,),  # CURLY LOOP
        (0x027bf, 0x027bf,),  # DOUBLE CURLY LOOP
        (0x02b1b, 0x02b1c,),  # BLACK LARGE SQUARE      ..WHITE LARGE SQUARE
        (0x02b50, 0x02b50,),  # WHITE MEDIUM STAR
        (0x02b55, 0x02b55,),  # HEAVY LARGE CIRCLE
        (0x03030, 0x03030,),  # WAVY DASH
        (0x0303d, 0x0303d,),  # PART ALTERNATION MARK
        (0x03297, 0x03297,),  # CIRCLED IDEOGRAPH CONGRATULATION
        (0x03299, 0x03299,),  # CIRCLED IDEOGRAPH SECRET
        (0x1f30d, 0x1f30f,),  # EARTH GLOBE EUROPE-AFRIC..EARTH GLOBE ASIA-AUSTRAL
        (0x1f315, 0x1f315,),  # FULL MOON SYMBOL
        (0x1f31c, 0x1f31c,),  # LAST QUARTER MOON WITH FACE
        (0x1f378, 0x1f378,),  # COCKTAIL GLASS
        (0x1f393, 0x1f393,),  # GRADUATION CAP
        (0x1f3a7, 0x1f3a7,),  # HEADPHONE
        (0x1f3ac, 0x1f3ae,),  # CLAPPER BOARD           ..VIDEO GAME
        (0x1f3c2, 0x1f3c2,),  # SNOWBOARDER
        (0x1f3c4, 0x1f3c4,),  # SURFER
        (0x1f3c6, 0x1f3c6,),  # TROPHY
        (0x1f3ca, 0x1f3ca,),  # SWIMMER
        (0x1f3e0, 0x1f3e0,),  # HOUSE BUILDING
        (0x1f3ed, 0x1f3ed,),  # FACTORY
        (0x1f408, 0x1f408,),  # CAT
        (0x1f415, 0x1f415,),  # DOG
        (0x1f41f, 0x1f41f,),  # FISH
        (0x1f426, 0x1f426,),  # BIRD
        (0x1f442, 0x1f442,),  # EAR
        (0x1f446, 0x1f449,),  # WHITE UP POINTING BACKHA..WHITE RIGHT POINTING BAC
        (0x1f44d, 0x1f44e,),  # THUMBS UP SIGN          ..THUMBS DOWN SIGN
        (0x1f453, 0x1f453,),  # EYEGLASSES
        (0x1f46a, 0x1f46a,),  # FAMILY
        (0x1f47d, 0x1f47d,),  # EXTRATERRESTRIAL ALIEN
        (0x1f4a3, 0x1f4a3,),  # BOMB
        (0x1f4b0, 0x1f4b0,),  # MONEY BAG
        (0x1f4b3, 0x1f4b3,),  # CREDIT CARD
        (0x1f4bb, 0x1f4bb,),  # PERSONAL COMPUTER
        (0x1f4bf, 0x1f4bf,),  # OPTICAL DISC
        (0x1f4cb, 0x1f4cb,),  # CLIPBOARD
        (0x1f4da, 0x1f4da,),  # BOOKS
        (0x1f4df, 0x1f4df,),  # PAGER
        (0x1f4e4, 0x1f4e6,),  # OUTBOX TRAY             ..PACKAGE
        (0x1f4ea, 0x1f4ed,),  # CLOSED MAILBOX WITH LOWE..OPEN MAILBOX WITH LOWERE
        (0x1f4f7, 0x1f4f7,),  # CAMERA
        (0x1f4f9, 0x1f4fb,),  # VIDEO CAMERA            ..RADIO
        (0x1f508, 0x1f508,),  # SPEAKER
        (0x1f50d, 0x1f50d,),  # LEFT-POINTING MAGNIFYING GLASS
        (0x1f512, 0x1f513,),  # LOCK                    ..OPEN LOCK
        (0x1f550, 0x1f567,),  # CLOCK FACE ONE OCLOCK   ..CLOCK FACE TWELVE-THIRTY
        (0x1f610, 0x1f610,),  # NEUTRAL FACE
        (0x1f687, 0x1f687,),  # METRO
        (0x1f68d, 0x1f68d,),  # ONCOMING BUS
        (0x1f691, 0x1f691,),  # AMBULANCE
        (0x1f694, 0x1f694,),  # ONCOMING POLICE CAR
        (0x1f698, 0x1f698,),  # ONCOMING AUTOMOBILE
        (0x1f6ad, 0x1f6ad,),  # NO SMOKING SYMBOL
        (0x1f6b2, 0x1f6b2,),  # BICYCLE
        (0x1f6b9, 0x1f6ba,),  # MENS SYMBOL             ..WOMENS SYMBOL
        (0x1f6bc, 0x1f6bc,),  # BABY SYMBOL
    ),
}


VS15_OVERRIDES = {
    'bobcat': _SET_cdb8c790,
    'extraterm': _SET_c137548c,
    'konsole': _SET_c137548c,
    'putty': _SET_c137548c,
    'rio': _SET_c137548c,
    'teraterm': _SET_c137548c,
    'terminal.app': _SET_c137548c,
    'terminal.exe': _SET_c137548c,
    'vte': _SET_c137548c,
    'wezterm': _SET_c137548c,
    'xterm': _SET_c137548c,
    'zellij': _SET_c137548c,
    'alacritty': _SET_c137548c,
    'cmd.exe': _SET_c137548c,
    'contour': _SET_c137548c,
    'foot': _SET_c137548c,
    'iterm2': _SET_c137548c,
    'libvterm': _SET_c137548c,
    'mlterm': _SET_c137548c,
    'qtermwidget': _SET_c137548c,
    'rxvt-unicode': _SET_c137548c,
    'screen': _SET_c137548c,
    'securecrt': _SET_b708b91e,
    'st': _SET_c137548c,
    'terminology': _SET_c137548c,
    'tmux': _SET_c137548c,
    'xterm.js': _SET_c137548c,
    'zutty': _SET_c137548c,
}
