"""
Exports SRI_OVERRIDES table keyed by canonical terminal software name.

This code generated by python wcwidth project from ucs-detect data.
"""
# pylint: skip-file
_SET_58496605 = {
    'narrower': (
        (0x1f1e6, 0x1f1ff,),  # Regional Indicator Symbo..Regional Indicator Symbo
    ),
    'wider': (
    ),
}


SRI_OVERRIDES = {
    'alacritty': _SET_58496605,
    'apple_terminal': _SET_58496605,
    'cmd.exe': _SET_58496605,
    'extraterm': _SET_58496605,
    'foot': _SET_58496605,
    'mlterm': _SET_58496605,
    'putty': _SET_58496605,
    'qtermwidget': _SET_58496605,
    'rio': _SET_58496605,
    'rxvt-unicode': _SET_58496605,
    'screen': _SET_58496605,
    'securecrt': _SET_58496605,
    'st': _SET_58496605,
    'teraterm': _SET_58496605,
    'terminal.exe': _SET_58496605,
    'terminology': _SET_58496605,
    'vte': _SET_58496605,
    'weston-terminal': _SET_58496605,
    'wezterm': _SET_58496605,
    'xterm': _SET_58496605,
    'xterm.js': _SET_58496605,
    'zellij': _SET_58496605,
    'zutty': _SET_58496605,
}
