"""
Exports function list_versions() for unicode version level support.

This code generated by wcwidth/bin/update-tables.py on 2026-01-26 23:59:09 UTC.
"""

from __future__ import annotations


def list_versions() -> tuple[str, ...]:
    """
    Return Unicode version levels supported by this module release.

    Any of the version strings returned may be used as keyword argument
    ``unicode_version`` to the ``wcwidth()`` family of functions.

    :returns: Supported Unicode version numbers in ascending sorted order.
    """
    return (
        "17.0.0",
    )
