from typing import Literal, Sequence, Optional

def _bisearch(ucs: str, table: Sequence[tuple[int, int]]) -> Literal[0, 1]: ...
def wcwidth(wc: str, unicode_version: str = "auto") -> int: ...
def wcswidth(pwcs: str, n: Optional[int] = None, unicode_version: str = "auto") -> int: ...
def _wcversion_value(ver_string: str) -> tuple[int, ...]: ...
def _wcmatch_version(given_version: str) -> str: ...
